const pages = {
  'A1_Neonataladmissionsheet.html': require('./assets/A1_Neonataladmissionsheet.html'),
  'A2_Paedicatricadmissionsheet.html': require('./assets/A2_Paedicatricadmissionsheet.html'),
  'A3_CCP.html': require('./assets/A3_CCP.html'),
  'A4_NeonatalReview.html': require('./assets/A4_NeonatalReview.html'),
  'A5_NeonatalAudit.html': require('./assets/A5_NeonatalAudit.html'),
  'A6_Neonatalreferral.html': require('./assets/A6_Neonatalreferral.html'),
  'ART.htm': require('./assets/ART.htm'),
  'Anaemia.htm': require('./assets/Anaemia.htm'),
  'Antibiotic and Aminophylline doses.html': require('./assets/Antibiotic and Aminophylline doses.html'),
  'Appendices.html': require('./assets/Appendices.html'),
  'Appendix.html': require('./assets/Appendix.html'),
  'Bleeding.htm': require('./assets/Bleeding.htm'),
  'Breathing difficulties in the YI.html': require('./assets/Breathing difficulties in the YI.html'),
  'Breathing difficulties in the new born.html': require('./assets/Breathing difficulties in the new born.html'),
  'Bubble CPAP.html': require('./assets/Bubble CPAP.html'),
  'C10_Hypothermia.html': require('./assets/C10_Hypothermia.html'),
  'C111416_Emergencies.html': require('./assets/C111416_Emergencies.html'),
  'C11_Hypoglycaemia.html': require('./assets/C11_Hypoglycaemia.html'),
  'C12_18fluids.html': require('./assets/C12_18fluids.html'),
  'C12_fluidmanagement.html': require('./assets/C12_fluidmanagement.html'),
  'C13_Jaundice.html': require('./assets/C13_Jaundice.html'),
  'C14_Shock.html': require('./assets/C14_Shock.html'),
  'C15_17Infections.html': require('./assets/C15_17Infections.html'),
  'C15_Sepsis.html': require('./assets/C15_Sepsis.html'),
  'C16_ComaConvulsions.html': require('./assets/C16_ComaConvulsions.html'),
  'C17_Meningitis.html': require('./assets/C17_Meningitis.html'),
  'C18_Diarrhoea.html': require('./assets/C18_Diarrhoea.html'),
  'C19_20Transport.html': require('./assets/C19_20Transport.html'),
  'C19_Referral.html': require('./assets/C19_Referral.html'),
  'C1_Triage.html': require('./assets/C1_Triage.html'),
  'C20_Discharge.html': require('./assets/C20_Discharge.html'),
  'C21_essential.html': require('./assets/C21_essential.html'),
  'C22_23Audit.html': require('./assets/C22_23Audit.html'),
  'C22_audit.html': require('./assets/C22_audit.html'),
  'C23_goodclinicalpractice.html': require('./assets/C23_goodclinicalpractice.html'),
  'C24_Infectionprevention.html': require('./assets/C24_Infectionprevention.html'),
  'C2_RoutineCare.html': require('./assets/C2_RoutineCare.html'),
  'C3_4_Resuscitation.html': require('./assets/C3_4_Resuscitation.html'),
  'C3_ResuscNewborn.html': require('./assets/C3_ResuscNewborn.html'),
  'C4_ResuscInfant.html': require('./assets/C4_ResuscInfant.html'),
  'C567_Breathing.html': require('./assets/C567_Breathing.html'),
  'C5_Breathing difficulties.html': require('./assets/C5_Breathing difficulties.html'),
  'C6_oxygen.html': require('./assets/C6_oxygen.html'),
  'C7_CPAP.html': require('./assets/C7_CPAP.html'),
  'C8_Asphyxia.html': require('./assets/C8_Asphyxia.html'),
  'C910_Preterm.html': require('./assets/C910_Preterm.html'),
  'C9_Preterm.html': require('./assets/C9_Preterm.html'),
  'CCP.htm': require('./assets/CCP.htm'),
  'Cardiac Failure.htm': require('./assets/Cardiac Failure.htm'),
  'Charts1.htm': require('./assets/Charts1.htm'),
  'Coma and convulsions.html': require('./assets/Coma and convulsions.html'),
  'Congenitalheart.htm': require('./assets/Congenitalheart.htm'),
  'Day 3.html': require('./assets/Day 3.html'),
  'Day 4.html': require('./assets/Day 4.html'),
  'Diagnostic alg.htm': require('./assets/Diagnostic alg.htm'),
  'Diarrhoea and dehydration.html': require('./assets/Diarrhoea and dehydration.html'),
  'Discharge from hospital.html': require('./assets/Discharge from hospital.html'),
  'E10_Syringepump.html': require('./assets/E10_Syringepump.html'),
  'E11_phototherapy.html': require('./assets/E11_phototherapy.html'),
  'E1_Suctionpump.html': require('./assets/E1_Suctionpump.html'),
  'E2_Pulse oximeter.html': require('./assets/E2_Pulse oximeter.html'),
  'E3_Oxygen concentrator.html': require('./assets/E3_Oxygen concentrator.html'),
  'E4_Oxygen cylinder.html': require('./assets/E4_Oxygen cylinder.html'),
  'E5_Oxygen splitter.html': require('./assets/E5_Oxygen splitter.html'),
  'E6_Oxygen therapy.html': require('./assets/E6_Oxygen therapy.html'),
  'E8_Radiant Warmer.html': require('./assets/E8_Radiant Warmer.html'),
  'E9_Glucometer.html': require('./assets/E9_Glucometer.html'),
  'Equipment.html': require('./assets/Equipment.html'),
  'Essential equipment and maintenance.html': require('./assets/Essential equipment and maintenance.html'),
  'Fluid management in a NYI.html': require('./assets/Fluid management in a NYI.html'),
  'Formulary coin.html': require('./assets/Formulary coin.html'),
  'Formulary.html': require('./assets/Formulary.html'),
  'HIVTB.htm': require('./assets/HIVTB.htm'),
  'How to deliver oxygen to a NYI.html': require('./assets/How to deliver oxygen to a NYI.html'),
  'How to manage birth asphyxia.html': require('./assets/How to manage birth asphyxia.html'),
  'How to manage hypoglycaemia in NYI.html': require('./assets/How to manage hypoglycaemia in NYI.html'),
  'How to manage jaundice.html': require('./assets/How to manage jaundice.html'),
  'Hypertension.htm': require('./assets/Hypertension.htm'),
  'Maintenance Oral and IV fluids (III).html': require('./assets/Maintenance Oral and IV fluids (III).html'),
  'Management of Convulsions (II).html': require('./assets/Management of Convulsions (II).html'),
  'Meningitis2.html': require('./assets/Meningitis2.html'),
  'Moyo Chart.html': require('./assets/Moyo Chart.html'),
  'NYI care pathway.html': require('./assets/NYI care pathway.html'),
  'NYI stabilization,referral and transfer.html': require('./assets/NYI stabilization,referral and transfer.html'),
  'Neonatal admission sheet.html': require('./assets/Neonatal admission sheet.html'),
  'Nephritic.htm': require('./assets/Nephritic.htm'),
  'Nephrotic.htm': require('./assets/Nephrotic.htm'),
  'Ophthalmology.htm': require('./assets/Ophthalmology.htm'),
  'Paeds Mech Vent.htm': require('./assets/Paeds Mech Vent.htm'),
  'Pain Management.htm': require('./assets/Pain Management.htm'),
  'Paralysis.htm': require('./assets/Paralysis.htm'),
  'Physiotherapy.htm': require('./assets/Physiotherapy.htm'),
  'Resuscitation of the Young Infant.html': require('./assets/Resuscitation of the Young Infant.html'),
  'Resuscitation of the newborn.html': require('./assets/Resuscitation of the newborn.html'),
  'Routine care of the normal new born.html': require('./assets/Routine care of the normal new born.html'),
  'Schistosomiasis.htm': require('./assets/Schistosomiasis.htm'),
  'Seizures.htm': require('./assets/Seizures.htm'),
  'Sepsis in NYI.html': require('./assets/Sepsis in NYI.html'),
  'Sexual Abuse.htm': require('./assets/Sexual Abuse.htm'),
  'Sicklecelldisease.htm': require('./assets/Sicklecelldisease.htm'),
  'Temperature control in NYI.html': require('./assets/Temperature control in NYI.html'),
  'The low birth weight and premature infant.html': require('./assets/The low birth weight and premature infant.html'),
  'The management of shock.html': require('./assets/The management of shock.html'),
  'Triage of the sick infant.html': require('./assets/Triage of the sick infant.html'),
  'Umodzi.htm': require('./assets/Umodzi.htm'),
  'WA_phototherapy.html': require('./assets/WA_phototherapy.html'),
  'WB_convulsions.html': require('./assets/WB_convulsions.html'),
  'WC_Maintenance Oral and IV fluids.html': require('./assets/WC_Maintenance Oral and IV fluids.html'),
  'WD_Antibiotic and Aminophylline doses.html': require('./assets/WD_Antibiotic and Aminophylline doses.html'),
  'WE_HIEgrading.html': require('./assets/WE_HIEgrading.html'),
  'WF_Hypoglycaemia.html': require('./assets/WF_Hypoglycaemia.html'),
  'WG_10perc_glc.html': require('./assets/WG_10perc_glc.html'),
  'WH_neoresusc.html': require('./assets/WH_neoresusc.html'),
  'WI_YIresusc.html': require('./assets/WI_YIresusc.html'),
  'WJ_TRY.html': require('./assets/WJ_TRY.html'),
  'WK_shock.html': require('./assets/WK_shock.html'),
  'Wall Charts.html': require('./assets/Wall Charts.html'),
  'When to start phototherapy for jaundice (I).html': require('./assets/When to start phototherapy for jaundice (I).html'),
  'Young infant and child admission sheet.html': require('./assets/Young infant and child admission sheet.html'),
  '_chapters.htm': require('./assets/_chapters.htm'),
  '_section_Abbreviations.htm': require('./assets/_section_Abbreviations.htm'),
  '_section_HIV.htm': require('./assets/_section_HIV.htm'),
  '_section_TB.htm': require('./assets/_section_TB.htm'),
  '_section_cardiology.htm': require('./assets/_section_cardiology.htm'),
  '_section_emergencies.htm': require('./assets/_section_emergencies.htm'),
  '_section_formulary.htm': require('./assets/_section_formulary.htm'),
  '_section_gastro.htm': require('./assets/_section_gastro.htm'),
  '_section_general.htm': require('./assets/_section_general.htm'),
  '_section_hematology.htm': require('./assets/_section_hematology.htm'),
  '_section_infections.htm': require('./assets/_section_infections.htm'),
  '_section_malnutrition.htm': require('./assets/_section_malnutrition.htm'),
  '_section_neonatology.htm': require('./assets/_section_neonatology.htm'),
  '_section_nephrology.htm': require('./assets/_section_nephrology.htm'),
  '_section_neurology.htm': require('./assets/_section_neurology.htm'),
  '_section_other.htm': require('./assets/_section_other.htm'),
  '_section_pulmo.htm': require('./assets/_section_pulmo.htm'),
  '_section_support.htm': require('./assets/_section_support.htm'),
  'abmal.htm': require('./assets/abmal.htm'),
  'ackno.htm': require('./assets/ackno.htm'),
  'acknowledgements.html': require('./assets/acknowledgements.html'),
  'acronyms.html': require('./assets/acronyms.html'),
  'airway_obstruction.htm': require('./assets/airway_obstruction.htm'),
  'aki.htm': require('./assets/aki.htm'),
  'anaemiahiv.htm': require('./assets/anaemiahiv.htm'),
  'anaphylaxis.htm': require('./assets/anaphylaxis.htm'),
  'asthma.htm': require('./assets/asthma.htm'),
  'audiology.html': require('./assets/audiology.html'),
  'background.htm': require('./assets/background.htm'),
  'backgroundchapters.html': require('./assets/backgroundchapters.html'),
  'bibl.html': require('./assets/bibl.html'),
  'breastfeeding.html': require('./assets/breastfeeding.html'),
  'bronchiolitis.htm': require('./assets/bronchiolitis.htm'),
  'cardiac.htm': require('./assets/cardiac.htm'),
  'careoflowbirth.htm': require('./assets/careoflowbirth.htm'),
  'chapters.htm': require('./assets/chapters.htm'),
  'charts.htm': require('./assets/charts.htm'),
  'chest pain.htm': require('./assets/chest pain.htm'),
  'cholera.htm': require('./assets/cholera.htm'),
  'ckd.htm': require('./assets/ckd.htm'),
  'coin.htm': require('./assets/coin.htm'),
  'coma.htm': require('./assets/coma.htm'),
  'compli.htm': require('./assets/compli.htm'),
  'contributor2.html': require('./assets/contributor2.html'),
  'contributors.html': require('./assets/contributors.html'),
  'conv.html': require('./assets/conv.html'),
  'convulsion.htm': require('./assets/convulsion.htm'),
  'cp.htm': require('./assets/cp.htm'),
  'cpt.htm': require('./assets/cpt.htm'),
  'day 1.html': require('./assets/day 1.html'),
  'day 2.html': require('./assets/day 2.html'),
  'demo.html': require('./assets/demo.html'),
  'derma.htm': require('./assets/derma.htm'),
  'dermatology.htm': require('./assets/dermatology.htm'),
  'disc.htm': require('./assets/disc.htm'),
  'disccoin.htm': require('./assets/disccoin.htm'),
  'disccoin2.html': require('./assets/disccoin2.html'),
  'discharge.htm': require('./assets/discharge.htm'),
  'dysentery.htm': require('./assets/dysentery.htm'),
  'electrolyte.htm': require('./assets/electrolyte.htm'),
  'ent.html': require('./assets/ent.html'),
  'feedcharts.htm': require('./assets/feedcharts.htm'),
  'feeding lbw.html': require('./assets/feeding lbw.html'),
  'fluid_management.htm': require('./assets/fluid_management.htm'),
  'foreword.html': require('./assets/foreword.html'),
  'forward.html': require('./assets/forward.html'),
  'gastro_acute.htm': require('./assets/gastro_acute.htm'),
  'gastro_chronic.htm': require('./assets/gastro_chronic.htm'),
  'heart disease infection.htm': require('./assets/heart disease infection.htm'),
  'hus.htm': require('./assets/hus.htm'),
  'hydrocephalus.htm': require('./assets/hydrocephalus.htm'),
  'icp.htm': require('./assets/icp.htm'),
  'immun.htm': require('./assets/immun.htm'),
  'infections.html': require('./assets/infections.html'),
  'introduction.html': require('./assets/introduction.html'),
  'investigationstb.htm': require('./assets/investigationstb.htm'),
  'iris.htm': require('./assets/iris.htm'),
  'iso.htm': require('./assets/iso.htm'),
  'kmc.htm': require('./assets/kmc.htm'),
  'kmc2.html': require('./assets/kmc2.html'),
  'malaria.htm': require('./assets/malaria.htm'),
  'malnutrition.htm': require('./assets/malnutrition.htm'),
  'managm.htm': require('./assets/managm.htm'),
  'meningitis.htm': require('./assets/meningitis.htm'),
  'mouth.htm': require('./assets/mouth.htm'),
  'neojaun.htm': require('./assets/neojaun.htm'),
  'neoresusc.htm': require('./assets/neoresusc.htm'),
  'neosepsis.htm': require('./assets/neosepsis.htm'),
  'neosurg.htm': require('./assets/neosurg.htm'),
  'neurohiv.htm': require('./assets/neurohiv.htm'),
  'new.html': require('./assets/new.html'),
  'nutrihiv.htm': require('./assets/nutrihiv.htm'),
  'occupational.html': require('./assets/occupational.html'),
  'oxygen.htm': require('./assets/oxygen.htm'),
  'pd.htm': require('./assets/pd.htm'),
  'picu.htm': require('./assets/picu.htm'),
  'pneumonia.html': require('./assets/pneumonia.html'),
  'poisoning.htm': require('./assets/poisoning.htm'),
  'poisoning1.htm': require('./assets/poisoning1.htm'),
  'poster.htm': require('./assets/poster.htm'),
  'pulmohiv.htm': require('./assets/pulmohiv.htm'),
  'rabies.htm': require('./assets/rabies.htm'),
  'resus.htm': require('./assets/resus.htm'),
  'salmonella.htm': require('./assets/salmonella.htm'),
  'shock.htm': require('./assets/shock.htm'),
  'short.htm': require('./assets/short.htm'),
  'specialsituation.htm': require('./assets/specialsituation.htm'),
  'staging.htm': require('./assets/staging.htm'),
  'standardpro.htm': require('./assets/standardpro.htm'),
  'surv.htm': require('./assets/surv.htm'),
  'swollen.htm': require('./assets/swollen.htm'),
  'tbm.htm': require('./assets/tbm.htm'),
  'tetanus.htm': require('./assets/tetanus.htm'),
  'thejaudiced.htm': require('./assets/thejaudiced.htm'),
  'thelimpingchild.htm': require('./assets/thelimpingchild.htm'),
  'therapeu.htm': require('./assets/therapeu.htm'),
  'title.html': require('./assets/title.html'),
  'trauma.htm': require('./assets/trauma.htm'),
  'treatfail.htm': require('./assets/treatfail.htm'),
  'treatmentfai.htm': require('./assets/treatmentfai.htm'),
  'treatmenttb.htm': require('./assets/treatmenttb.htm'),
  'triage.htm': require('./assets/triage.htm'),
  'triage2022.html': require('./assets/triage2022.html'),
  'type1diabetes.htm': require('./assets/type1diabetes.htm'),
  'uti.htm': require('./assets/uti.htm'),
  'vital_signs.htm': require('./assets/vital_signs.htm'),
};

export default pages;
