MYAPP_UPLOAD_FILE=C:/Users/dchen/Desktop/og/open_guidelines/credentials/android/keystore.jks
MYAPP_UPLOAD_STORE_PASSWORD=9841440a7cc2a6246def24753e5d200d
MYAPP_UPLOAD_KEY_ALIAS=595cb3694f5d5d307d7c9ccf8eb24cd6
MYAPP_UPLOAD_KEY_PASSWORD=ec2b5b60f11042bbeae3e0c733af5136